	steps:
	  - name: {insert step name here}

	```

</details>
1. Next, you want to run the nosetests command to test your code and report on code coverage.

	```
	nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
	```
	Since you are running a single command, you do not have to use the pipe `|` operator with `run`.

	<details><summary>Click here for a hint.</summary>

```yaml
	  - name: Run unit tests with nose
	    run: {insert command here}
	```

</details>

Double-check that your work matches the solution below.

### Solution

<details><summary>Click here for the answer.</summary>

Replace the workflow.yml file with the code snippet below. You can also copy relevant parts of the code. Be sure to indent properly:

```yaml
name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
	  - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

	  - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with nose
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
